# Generated by Django 3.0.7 on 2020-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wonuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonuser',
            name='clue3solved',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='wonuser',
            name='clue1solved',
            field=models.DateTimeField(null='True'),
        ),
        migrations.AlterField(
            model_name='wonuser',
            name='clue2solved',
            field=models.DateTimeField(null='True'),
        ),
    ]
