# Generated by Django 3.0.7 on 2020-06-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200611_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_mate_email',
            field=models.CharField(blank='True', default='', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
