# Generated by Django 3.0.7 on 2020-06-18 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200618_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='cluedead',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 18, 10, 36, 28, 422403, tzinfo=utc), null=True),
        ),
    ]
