# Generated by Django 3.0.7 on 2020-06-19 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200618_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='cluedead',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 7, 37, 20, 954253, tzinfo=utc), null=True),
        ),
    ]
