# Generated by Django 3.0.7 on 2020-06-19 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200619_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='cluedead',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 14, 39, 38, 321760, tzinfo=utc), null=True),
        ),
    ]
