# Generated by Django 3.0.7 on 2020-06-19 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200619_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='dead',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='cluedead',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 18, 0, 41, 550175, tzinfo=utc), null=True),
        ),
    ]
